#! /bin/sh
#
#  Für SuSE-Linux Distributionen
#
#  1. Die Pfade, den Benutzer u. die Gruppe im Script anpassen.
#
#  2. Zum automatischen Starten bei SuSE-Linux-Distribution
#     Datei nach /sbin/init.de/ebkus kopieren und 2 Links in 
#      /sbin/init.d/rc3.d anlegen!
#     ln -s ../init.d/ebkus S25ebkus
#     ln -s ../init.de/ebkus K25ebkus
#
#  3. Die folgende Abfrage in der Datei /etc/rc.config eintragen:
#     START_EBKUS="yes"
#
# /sbin/init.d/ebkus
#
#   and symbolic its link
#
# /sbin/ebkus
#
#  4. ebkus_server.sh aus ebkus/stuff nach ebkus/ kopieren !

. /etc/rc.config

# Determine the base and follow a runlevel link name.
base=${0##*/}
link=${base#*[SK][0-9][0-9]}

# Force execution if not called by a runlevel directory.
test $link = $base && START_EBKUS=yes
test "$START_EBKUS" = yes || exit 0

# The echo return value for success (defined in /etc/rc.config).
return=$rc_done
case "$1" in
    start)
	if test -f /home/ebkus/public_html/ebkus/ebkus_server.sh ; then
		echo "Starting EBKuS-Server."
		startproc -u ebkus -g users /home/ebkus/public_html/ebkus/ebkus_server.sh || return=$rc_failed
		echo -e "$return"
	fi
	;;
    stop)
	echo -n "Shutting down EBKuS_Server:"
	killproc -TERM /home/ebkus/public_html/ebkus/ebkus_server.sh || return=$rc_failed
	echo -e "$return"
	;;
    restart|reload)
	echo -n "Restarting service EBKuS-Server."
	$0 stop  &&  $0 start  ||  return=$rc_failed
	echo -e "$return"
	;;
    *)
	echo "Usage: $0 {start|restart}"
	exit 1
	;;
esac

# Inform the caller not only verbosely and set an exit status.
test "$return" = "$rc_done" || exit 1
exit 0
